name: Build XPEViewer

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read

env:
  SRC_PATH: ${{ github.workspace }}/src
  SRC_PATH_WIN: ${{ github.workspace }}\src
  RELEASE_PATH: ${{ github.workspace }}/src/release

jobs:
  build-windows-64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: ${{ env.SRC_PATH }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: ${{ github.workspace }}
          modules: qtscript

      - name: Build
        shell: cmd
        working-directory: ${{ env.SRC_PATH }}
        run: |
          set VSVARS_PATH="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set QMAKE_PATH="${{ github.workspace }}\Qt\5.15.2\msvc2019_64\bin\qmake.exe"
          set SEVENZIP_PATH="C:\Program Files\7-Zip\7z.exe"
          set INNOSETUP_PATH="C:\Program Files (x86)\Inno Setup 6\ISCC.exe"

          set X_BUILD_NAME=xpeviewer
          set X_BUILD_PREFIX=win64
          set X_SOURCE_PATH=${{ env.SRC_PATH_WIN }}
          for /f "delims=" %%x in ('type "%X_SOURCE_PATH%\release_version.txt"') do set X_RELEASE_VERSION=%%x

          echo on
          call "%X_SOURCE_PATH%\build_win_generic.cmd"

          dir "%X_SOURCE_PATH%\release\*.zip" >nul 2>&1
          if %ERRORLEVEL% neq 0 (
            echo "ZIP file does not exist"
            exit /b 1
          )

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xpeviewer-windows-x64
          path: |
            ${{ env.RELEASE_PATH }}/*.zip
            ${{ env.RELEASE_PATH }}/*.exe
          if-no-files-found: error

  publish-release:
    runs-on: ubuntu-latest
    needs:
      - build-windows-64
    permissions:
      contents: write
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          merge-multiple: true

      - name: Upload Release as Download
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN || github.token }}
          tag_name: Beta
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            release-assets/*
